# Generated by Django 3.1.4 on 2020-12-26 20:37

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='publish_year',
            field=models.DateField(default=datetime.date.today, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdb_score',
            field=models.TextField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='storyline',
            field=models.TextField(max_length=200, verbose_name='StoryLine'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
