# Generated by Django 3.1.4 on 2020-12-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieApp', '0003_auto_20201227_0110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='publish_year',
            field=models.IntegerField(null=True, verbose_name='Year'),
        ),
    ]
